application: somechat156
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: example.py

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
